// Generated by gencpp from file dashgo_bringup/ultrasonicRequest.msg
// DO NOT EDIT!


#ifndef DASHGO_BRINGUP_MESSAGE_ULTRASONICREQUEST_H
#define DASHGO_BRINGUP_MESSAGE_ULTRASONICREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dashgo_bringup
{
template <class ContainerAllocator>
struct ultrasonicRequest_
{
  typedef ultrasonicRequest_<ContainerAllocator> Type;

  ultrasonicRequest_()
    {
    }
  ultrasonicRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ultrasonicRequest_

typedef ::dashgo_bringup::ultrasonicRequest_<std::allocator<void> > ultrasonicRequest;

typedef boost::shared_ptr< ::dashgo_bringup::ultrasonicRequest > ultrasonicRequestPtr;
typedef boost::shared_ptr< ::dashgo_bringup::ultrasonicRequest const> ultrasonicRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dashgo_bringup

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dashgo_bringup/ultrasonicRequest";
  }

  static const char* value(const ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ultrasonicRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::dashgo_bringup::ultrasonicRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DASHGO_BRINGUP_MESSAGE_ULTRASONICREQUEST_H
