// Generated by gencpp from file dashgo_bringup/ultrasonic.msg
// DO NOT EDIT!


#ifndef DASHGO_BRINGUP_MESSAGE_ULTRASONIC_H
#define DASHGO_BRINGUP_MESSAGE_ULTRASONIC_H

#include <ros/service_traits.h>


#include <dashgo_bringup/ultrasonicRequest.h>
#include <dashgo_bringup/ultrasonicResponse.h>


namespace dashgo_bringup
{

struct ultrasonic
{

typedef ultrasonicRequest Request;
typedef ultrasonicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ultrasonic
} // namespace dashgo_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dashgo_bringup::ultrasonic > {
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::dashgo_bringup::ultrasonic&) { return value(); }
};

template<>
struct DataType< ::dashgo_bringup::ultrasonic > {
  static const char* value()
  {
    return "dashgo_bringup/ultrasonic";
  }

  static const char* value(const ::dashgo_bringup::ultrasonic&) { return value(); }
};


// service_traits::MD5Sum< ::dashgo_bringup::ultrasonicRequest> should match 
// service_traits::MD5Sum< ::dashgo_bringup::ultrasonic > 
template<>
struct MD5Sum< ::dashgo_bringup::ultrasonicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dashgo_bringup::ultrasonic >::value();
  }
  static const char* value(const ::dashgo_bringup::ultrasonicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dashgo_bringup::ultrasonicRequest> should match 
// service_traits::DataType< ::dashgo_bringup::ultrasonic > 
template<>
struct DataType< ::dashgo_bringup::ultrasonicRequest>
{
  static const char* value()
  {
    return DataType< ::dashgo_bringup::ultrasonic >::value();
  }
  static const char* value(const ::dashgo_bringup::ultrasonicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dashgo_bringup::ultrasonicResponse> should match 
// service_traits::MD5Sum< ::dashgo_bringup::ultrasonic > 
template<>
struct MD5Sum< ::dashgo_bringup::ultrasonicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dashgo_bringup::ultrasonic >::value();
  }
  static const char* value(const ::dashgo_bringup::ultrasonicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dashgo_bringup::ultrasonicResponse> should match 
// service_traits::DataType< ::dashgo_bringup::ultrasonic > 
template<>
struct DataType< ::dashgo_bringup::ultrasonicResponse>
{
  static const char* value()
  {
    return DataType< ::dashgo_bringup::ultrasonic >::value();
  }
  static const char* value(const ::dashgo_bringup::ultrasonicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DASHGO_BRINGUP_MESSAGE_ULTRASONIC_H
